### ISSUE TITLE
Please add a screen shot

### ISSUE THREAD

**Issue by unixorn** [Sulfurium/zsh-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots so that users can see what they look like without having to install them.

Thanks!

**Comment by Rheydskey** [comment]
Oh, we'll do it
Sorry for the time

**Comment by Woomymy** [comment]
![image](https://user-images.githubusercontent.com/57042741/100268535-7b29e180-2f55-11eb-954c-a7f01fa0b0cc.png)
What do you think of this? But I think I will modifiy somethings later.

**Comment by unixorn** [comment]
It shows off the theme, so it's good. Maybe add another line to also show what it looks like for non-root users?

**Comment by Woomymy** [comment]
hey! I have added a screenshot in the readme? What do you think of this?
